In [1]:
import numpy as np
np.__version__

'1.26.4'

In [3]:

arr1 = np.array([1,3,5,7,9])
arr2 = np.array((1,3,5,7,9))
type(arr1)

numpy.ndarray

In [5]:
arr3 = arr1

In [7]:
id(arr1)

1866989495536

In [9]:
id(arr3)

1866989495536

In [11]:
arr4 = arr1.copy()

In [13]:
id(arr4)

1867087113328

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [25]:
arr = np.arange(10)

In [27]:
len(arr)

10

In [29]:
arr.size

10

In [31]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
arr = np.linspace(0,10,5, retstep = True)
type(arr)

tuple

In [35]:
arr[0]

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.zeros(5, dtype = 'int64')

array([0, 0, 0, 0, 0], dtype=int64)

In [43]:
np.zeros(5, dtype='int64').dtype

dtype('int64')

In [45]:
arr = np.ones((2,3), dtype ='int_')

In [47]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [49]:
arr.dtype

dtype('int32')

In [51]:
arr.astype('float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [53]:
arr1 = np.array([111, 2.3,  True, False, False]) 
arr1

array([111. ,   2.3,   1. ,   0. ,   0. ])

In [55]:
arr2 = np.array([111, 2.3, 'python', 'abc']) 
arr2

array(['111', '2.3', 'python', 'abc'], dtype='<U32')

In [57]:
arr3 = np.array([111, True, 'abc']) 
arr3

array(['111', 'True', 'abc'], dtype='<U11')

In [59]:
a = np.array([1, 2, 3, 4, 5])
a[2]

3

In [61]:
a[-1]

5

In [63]:
a[:]

array([1, 2, 3, 4, 5])

In [65]:
a = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
a[1]

array([4, 5, 6])

In [69]:
a[-1]

array([7, 8, 9])

In [71]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
a[2][1]

8

In [75]:
a[2,1]

8

In [77]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [79]:
arr = np.arange(100)
arrMask = ( (arr % 5) == 0 ) 
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [81]:
arrMask = ( ( (arr % 5) == 0 )  & ( arr >0) )
arr[arrMask]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [83]:
a.size

9

In [85]:
a.shape

(3, 3)

In [87]:
a.ndim

2

In [89]:
a = np.arange(15)
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [91]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [95]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [97]:
a = np.array([2,5,1,3])
a.shape

(4,)

In [99]:
a = a.reshape((2,2))
a

array([[2, 5],
       [1, 3]])

In [101]:
a = np.arange(10)
b = a.reshape(2,5)
a[0] =-999

In [103]:
b

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [105]:
c = a.reshape(2,5).copy()
c[0,0] = 0
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [107]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

In [109]:
a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[9, 9]], axis=0)
b


array([[1, 2],
       [3, 4],
       [9, 9]])

In [111]:
c = np.append(a, [[9], [9]] , axis=1)
c

array([[1, 2, 9],
       [3, 4, 9]])

In [113]:
a = np.array([[1, 2, 3],[4, 5, 6]])
np.delete(a, 0)

array([2, 3, 4, 5, 6])

In [117]:
np.delete(a, (0,2,4))

array([2, 4, 6])

In [121]:
np.delete(a, 0, axis = 0)

array([[4, 5, 6]])

In [ ]:
np.delete(a, 1, axis=1)