In [1]:
import numpy as np

In [3]:
a = [1,2,3]

In [5]:
a+a

[1, 2, 3, 1, 2, 3]

In [7]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [9]:
b = np.array([1, 2, 3])

In [11]:
b*3

array([3, 6, 9])

In [13]:
b+b

array([2, 4, 6])

In [15]:
np.repeat(b,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


In [20]:
a+b

array([5, 7, 9])

In [22]:
a-b

array([-3, -3, -3])

In [24]:
a*b

array([ 4, 10, 18])

In [26]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

In [28]:
x = np.array([0, 1, 2, 3, 4, 5])


In [30]:
np.sqrt(x)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [33]:
np.exp(x)


array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [35]:
type(np.sqrt)


numpy.ufunc

In [37]:
type(np.exp)

numpy.ufunc

In [39]:
np.random.seed(123)
a = np.random.randint(1, 11, size=1000)

In [42]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.median(a)

5.0

In [48]:
np.sum(a)

5485

In [52]:
np.round(np.var(a),2)

8.19

In [54]:
np.round(np.mean(a),2)

5.48

In [56]:
np.round(np.std(a),2)

2.86

In [58]:
np.max(a)

10

In [60]:
np.min(a)

1

In [62]:
x=np.arange(1,11)

In [64]:
x.sum()

55

In [66]:
x.mean()

5.5

In [68]:
x.std()

2.8722813232690143

In [70]:
x.var()

8.25

In [72]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [74]:

y = np.arange(1,10)
y = y.reshape((3,-1))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
print(y.mean(axis=0))

[4. 5. 6.]


In [78]:
print(y.mean(axis=1))

[2. 5. 8.]


In [80]:
z = np.random.randint(10,size=1000)

In [83]:
z.max()

9

In [85]:
z.min()

0

In [87]:
(z>5).sum()

392

In [89]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
sorted(set(z))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [93]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [95]:
a.argmax()

4

In [97]:
a.argmin()

1